### PR TITLE
Menu manipulation

### PR DESCRIPTION
**Pull request by suzi216**
- Using JavaScript to manipulate the menu navigator.
- Use  JavaScript events.
- Adding more style to the mobile version

### CODE REVIEW

**Review by ishimwezachee — CHANGES_REQUESTED** [review]
Hi @Suzi216 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
 Linters is passing 👍 
The project is running successfully 👍 
PR is well described 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by suzi216** [comment]
@ishimwezachee I can not see any comments that you made to this pull request.
Could you please add them or let me know how to see them. 
Thanks!

**Comment by ishimwezachee** [comment]
I am very sorry, I added the comment and forget to click add comment. 
All I was just asking was  to increase the transparent of your background color so that it look similar to the one from figma design 
Your design          |  Figma design
:-------------------------:|:-------------------------:
image  |  image

**Review by omarsalem7 — APPROVED** [review]
Hi  @Suzi216 😊, 

# STATUS: APPROVED! 🥇 💯 

giphy

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
- Descriptive pull request ✔️
- Good descriptive readme ✔️
- No linter errors ✔️

Cheers and Happy coding!👏👏👏

## Optional suggestions

- [ ] [OPTIONAL] It will be better to ti give the mobile menu `100vh` to cover all layout
> your design 
image


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
